# Generated by Django 5.0.14 on 2026-04-22 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('category', models.CharField(choices=[('life', '生活'), ('learning', '学习'), ('travel', '旅游'), ('reflection', '感悟')], default='life', max_length=20, verbose_name='分类')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='文章图片')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
