"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0p++ie4uos-6$ajn0n%j53vpxo017+mn_r5q739*ldy9tl_=jj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_summernote',  # djangod 的富文本编辑器
    'blog',   # 博客应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 使用各应用下的 templates 目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# 静态文件 (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = []           # 可留空，已在应用内使用 static 目录
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
# 媒体文件（文章图片等）
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 云存储配置（生产环境使用）
USE_CLOUD_STORAGE = False  # 开发时设为 False，上线时改为 True

if USE_CLOUD_STORAGE:
    # 使用阿里云OSS
    DEFAULT_FILE_STORAGE = 'storages.backends.oss.AliyunOSSStorage'
    # 以下参数从环境变量或直接设置（请勿硬编码敏感信息）
    ALIYUN_OSS_ACCESS_KEY_ID = 'your-access-key-id'
    ALIYUN_OSS_ACCESS_KEY_SECRET = 'your-access-key-secret'
    ALIYUN_OSS_ENDPOINT = 'oss-cn-beijing.aliyuncs.com'       # 地域节点
    ALIYUN_OSS_BUCKET_NAME = 'your-bucket-name'
    ALIYUN_OSS_BUCKET_ACL = 'public-read'                     # 公共读
    MEDIA_URL = f'https://{ALIYUN_OSS_BUCKET_NAME}.{ALIYUN_OSS_ENDPOINT}/'
else:
    # 本地开发环境
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Summernote 配置
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'width': '100%',
        'height': '480',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
    },
}

# 和风天气 API 配置
WEATHER_CITY_NAME = '桂林'
WEATHER_LOCATION_ID = '101300517'  # 城市的 LocationID，可通过和风天气城市搜索接口获取，或直接用 city name
WEATHER_API_KEY = '67fead759b3c4c68b96bccb59312d885'  # 从控制台复制

# Django 本地缓存配置，用于缓存天气
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'weather-cache',
        'TIMEOUT': 3600,  # 默认缓存1小时
    }
}